export const ROUTER={
     AI_ML_IMAGE_PROCESSING : 'image-processing',
     MULBERRY_HEATMAP : 'mulberry-heatmap',
     DASHBOARD : 'dashboard',
     YARN_PO: 'yarn-po',
     YARN_LOTS: 'yarnlot',
     YARN_LOTS_QC: 'yarnlotqc',
     YARN_LOTS_PACKAGING: 'yarnlotpackaging',
     YARN_LOTS_APPROVAL: 'yarnlotapproval',
     YARN_SENT_FOR_TESTING: 'sent-for-twisting',
     TWISTING_UNIT : 'twisting-unit',
     REELERS : 'reelers',
     DETAILS: 'details',
     ID:'id',
     CRUD:'crud',
     REPORT:'report',
     USER_REPORT:'user',
     PNL_REPORT:'pnl',
     TRANSACTIONAL_REPORT:'transactional',
     PAYMENT_REPORT:'payment',
     INVENTORY_REPORT:'Inventory',
     COLLECTION_REPORT:'collection',
     RETURN:'return',
     RETAILER:'retailers',
     RETURN_RETAILER_SALES_ORDER:'sales-order-return',
     RETAILER_ORDERS:'retailer-orders',
     PRICE_PREDICTION:'cocoon-price-predictions',
     COUPON:'coupons',
     AUDIT_LIST:'audit',
     NAME:'name',
     SKUBATCH:'weaver-sku-batch',
     COCOON_ORDERS:'cocoon-orders',
     COCOON_PRICE_PREDICTIONS:'cocoon-price-predictions',
     AIML:'ai-ml',
     ACCOUNTS:'accounts',
     ACCOUNTS_WEAVER:'weaver-settlement',
     WEAVER_RETURN: 'weaver-sku-batch-return/weaver-return-orders-details',
     CATALOGUE_SAMPLE: 'catalog-sample'
}
