export const PUPAE_LIST = {
    CREDIT_WIP:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     SANCTIONED:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     DOCS_PENDING:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     SALES_REJECT:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     CREDIT_HOLD:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     MEETING_TO_BE_FIXED:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     CREDIT_REJECT:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     CUSTOMER_REJECT:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
     RFL:[
        { name:'CREDIT_WIP',isDisabled : false },
        { name:'SANCTIONED',isDisabled : false },
        { name:'DOCS_PENDING',isDisabled : false },
        { name:'SALES_REJECT',isDisabled : false },
        { name:'CREDIT_HOLD',isDisabled : false },
        { name:'MEETING_TO_BE_FIXED',isDisabled : false },
        { name:'CREDIT_REJECT',isDisabled : false },
        { name:'CUSTOMER_REJECT',isDisabled : false },
        { name:'RFL',isDisabled : false },
     ],
    
  
}